/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var evenSum = 0;
var limit = 1;
var fib = [1, 2];
var evenFib = [];


for (var i = 1; i <= limit; i++) {
  var num = fib[i] + fib[i - 1];
  
  if ((num % 2) === 0) {
    evenSum = evenSum + num;
    evenFib.push(num);
  } 
  
  if (num <= 4000000) {
    fib.push(num);
    limit++;
  }
}

console.log('Fibonacci sequence: \n' + fib + '\n');
console.log('Even Fibonacci sequence: \n' + evenFib + '\n');
console.log('Sum of even Fibconacci numbers: ' + evenSum + '\n');